### ISSUE TITLE
Correct answer rejected | Homework 3 Exercise 4

### ISSUE THREAD

**Issue by Hadrien-lcrx** [ctphoenix/Python-Course-Material#3]
On [Exercise 4](https://campus.datacamp.com/courses/using-python-for-research/case-study-1-caesar-cipher?ex=4), the following answer is rejected although it gives the correct output. The student's code uses a string directly, while the solution uses a list and then the `.join()` method to output a string. Apparently this is not the only exercise where several solutions are possible but only one is accepted, according to the [edX course discussion board](https://courses.edx.org/courses/course-v1:HarvardX+PH526x+1T2018/discussion/forum/).

### Suggestion
Specify which method should be used to get the results, or make the grader accept alternative solutions.

#### Student code
```python
def encoding (message, key):
    encoded_string = ''
    for char in message:
        position = positions[char]
        encoded_position = (position + key) % 27
        encoded_string = encoded_string + (alphabet[encoded_position])
    return encoded_string

key = 3
encoding (message, key)

encoded_message = encoding (message, key)
print (encoded_message)
```

#### Solution code
```python
def encoding(message, key 0):
    """
    This is a Caesar cipher.  Each letter in a message is shifted by a few
    characters in the alphabet, and returned.

    message:        A string you would like to encode or decode.  Must consist of
                    lowercase letters and spaces.
    key: An integer, indicating how many characters each letter in the
                    message will be shifted.
    """
    encoding_list = []
    for char in message:
        position = positions[char]
        encoded_position = (position + key) % 27
        encoding_list.append(alphabet[encoded_position])
    encoded_string = "".join(encoding_list)
    return encoded_string
    
encoded_message = encoding(message, 3)
print(encoded_message)
```

#### Student code
![image](https://user-images.githubusercontent.com/22552805/35521528-48706f88-051a-11e8-8eea-1e04071f1266.png)

#### Solution code
![image](https://user-images.githubusercontent.com/22552805/35521548-52c62806-051a-11e8-8a66-7fccb8e21353.png)

Cf tedhartley@aol.com, #85064
Cc @westonstearns

**Comment by ctphoenix** [comment]
Hi Hadrien,

On this question, I believe your issue is much more trivial than that. The grader did not expect whitespace before the parentheses in your calling of encoding. I have made it more flexible to accept extra whitespace in this instance. Hopefully that helps, but please let me know if not.

**Comment by Hadrien-lcrx** [comment]
@ctphoenix I think you're right. I now realize I didn't try it on this exercise, but this was an issue the student had with [Exercise 5](https://campus.datacamp.com/courses/using-python-for-research/case-study-1-caesar-cipher?ex=5) as well.

Another student wanted to let you know about a bug explained in this [thread](https://courses.edx.org/courses/course-v1:HarvardX+PH526x+1T2018/discussion/forum/672cbb528488a9be23afb5c1a417c99b498b461d/threads/5a6b03f024451a09ff00010d) in the Discussion Board.

**Comment by ctphoenix** [comment]
An issue with Exercise 5 would indeed be explained by the same mechanism. I've addressed the other issue you mentioned --- good catch.
